### ISSUE TITLE
Failure to compile for mac_arm64

### ISSUE THREAD

**Issue by geoffreygarrett** [tudat-team/tudat-bundle#1]
Although mac users with the new M1 arm-based chip can use the precompile packages on `conda`, these users seem unable to compile `tudat-bundle` using the this procedure.

- Seems that when they install boost, they are obtaining a non-arm compile variant to satisfy the boost dependency, **even though** there is a boost 1.72 mac_arm64 variant available on `conda-forge`

**Comment by FilippoOggionni** [comment]
Solved by specifying the arm64-specific channels for `conda-forge` and `tudat-team` in the `environment.yaml` file as follows. Apparently conda installs the non-arm64 version even on arm64-equipped machines.
```
name: tudat-bundle
channels:
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/tudat-team/osx-arm64
dependencies:
  - eigen
  - boost-cpp=1.72
  - tudat-resources
  - sofa-cmake
  - cspice-cmake
  - python=3.8
  - pybind11
  - pybind11-abi
  - numpy
  - pytest
```

**Comment by FilippoOggionni** [comment]
@ggarrett13 since the `cmake` package had to be installed manually, should it be listed as a dependency?

**Comment by geoffreygarrett** [comment]
@FilippoOggionni, could you make a note on `tudat-team/tudat-bundle` at the bottom of the procedure for now? I'm not sure it's necessary to list it a dependency. We'll leave this open until we're certain.
