### ISSUE TITLE
No description

### ISSUE THREAD

**Issue by cook-1229** [tudat-team/tudat-bundle#12]
GitHub page nowhere says what this project is.  Please add description to README.md.

**Comment by larshinueber** [comment]
Hi @cook-1229,
Thank you for your suggestion!

As mentioned in the `README.md` file, the `tudat-bundle` repository simplifies the parallel development of `tudat` in C++ and `tudatpy` in Python.
For more information on the Tudat project itself, take a look at the [project website](https://docs.tudat.space/en/latest/) and our [project Github page](https://github.com/tudat-team).

If you have any other questions, feel free to post them below 😀

**Comment by cook-1229** [comment]
Hello @larshinueber,
Thank you for your edit!
