### ISSUE TITLE
Add new tudatpy dependencies to environment.yaml

### ISSUE THREAD

**Issue by alopezrivera** [tudat-team/tudat-bundle#9]
[environment.yaml](https://github.com/tudat-team/tudat-bundle/blob/main/environment.yaml) should be updated to include:
- tqdm (`tudatpy.porkchop` module)
- astropy (`tudatpy.data.mpc` module)
- astroquery (`tudatpy.data.mpc` module)

**Comment by larshinueber** [comment]
As the dependencies have been added in #11, the issue is closed.
